// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/logic.proto

package logicpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogicProcessor_ProcessSensorData_FullMethodName = "/logic.LogicProcessor/ProcessSensorData"
)

// LogicProcessorClient is the client API for LogicProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogicProcessorClient interface {
	ProcessSensorData(ctx context.Context, in *SensorTriggerRequest, opts ...grpc.CallOption) (*SensorTriggerResponse, error)
}

type logicProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicProcessorClient(cc grpc.ClientConnInterface) LogicProcessorClient {
	return &logicProcessorClient{cc}
}

func (c *logicProcessorClient) ProcessSensorData(ctx context.Context, in *SensorTriggerRequest, opts ...grpc.CallOption) (*SensorTriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorTriggerResponse)
	err := c.cc.Invoke(ctx, LogicProcessor_ProcessSensorData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicProcessorServer is the server API for LogicProcessor service.
// All implementations must embed UnimplementedLogicProcessorServer
// for forward compatibility.
type LogicProcessorServer interface {
	ProcessSensorData(context.Context, *SensorTriggerRequest) (*SensorTriggerResponse, error)
	mustEmbedUnimplementedLogicProcessorServer()
}

// UnimplementedLogicProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicProcessorServer struct{}

func (UnimplementedLogicProcessorServer) ProcessSensorData(context.Context, *SensorTriggerRequest) (*SensorTriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSensorData not implemented")
}
func (UnimplementedLogicProcessorServer) mustEmbedUnimplementedLogicProcessorServer() {}
func (UnimplementedLogicProcessorServer) testEmbeddedByValue()                        {}

// UnsafeLogicProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicProcessorServer will
// result in compilation errors.
type UnsafeLogicProcessorServer interface {
	mustEmbedUnimplementedLogicProcessorServer()
}

func RegisterLogicProcessorServer(s grpc.ServiceRegistrar, srv LogicProcessorServer) {
	// If the following call pancis, it indicates UnimplementedLogicProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogicProcessor_ServiceDesc, srv)
}

func _LogicProcessor_ProcessSensorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicProcessorServer).ProcessSensorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicProcessor_ProcessSensorData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicProcessorServer).ProcessSensorData(ctx, req.(*SensorTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogicProcessor_ServiceDesc is the grpc.ServiceDesc for LogicProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogicProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logic.LogicProcessor",
	HandlerType: (*LogicProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSensorData",
			Handler:    _LogicProcessor_ProcessSensorData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/logic.proto",
}
