// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserInfoRequestFromGreenhouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequestFromGreenhouse) Reset() {
	*x = UserInfoRequestFromGreenhouse{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequestFromGreenhouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequestFromGreenhouse) ProtoMessage() {}

func (x *UserInfoRequestFromGreenhouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequestFromGreenhouse.ProtoReflect.Descriptor instead.
func (*UserInfoRequestFromGreenhouse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRequestFromGreenhouse) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

type UserInfoResponseFromGreenhouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FcmToken      string                 `protobuf:"bytes,2,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	LocationId    string                 `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	LocationName  string                 `protobuf:"bytes,5,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponseFromGreenhouse) Reset() {
	*x = UserInfoResponseFromGreenhouse{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponseFromGreenhouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponseFromGreenhouse) ProtoMessage() {}

func (x *UserInfoResponseFromGreenhouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponseFromGreenhouse.ProtoReflect.Descriptor instead.
func (*UserInfoResponseFromGreenhouse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoResponseFromGreenhouse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfoResponseFromGreenhouse) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *UserInfoResponseFromGreenhouse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfoResponseFromGreenhouse) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *UserInfoResponseFromGreenhouse) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

type UserEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmpty) Reset() {
	*x = UserEmpty{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmpty) ProtoMessage() {}

func (x *UserEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmpty.ProtoReflect.Descriptor instead.
func (*UserEmpty) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CreateUserRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FcmToken      string                 `protobuf:"bytes,4,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *UserResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAvatarRequest) Reset() {
	*x = UpdateAvatarRequest{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAvatarRequest) ProtoMessage() {}

func (x *UpdateAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAvatarRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAvatarRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type AvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvatarUrl     string                 `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarResponse) Reset() {
	*x = AvatarResponse{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarResponse) ProtoMessage() {}

func (x *AvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarResponse.ProtoReflect.Descriptor instead.
func (*AvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *AvatarResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateFcmTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FcmToken      string                 `protobuf:"bytes,2,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFcmTokenRequest) Reset() {
	*x = UpdateFcmTokenRequest{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFcmTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFcmTokenRequest) ProtoMessage() {}

func (x *UpdateFcmTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFcmTokenRequest.ProtoReflect.Descriptor instead.
func (*UpdateFcmTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateFcmTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateFcmTokenRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

type FcmTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FcmToken      string                 `protobuf:"bytes,1,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FcmTokenResponse) Reset() {
	*x = FcmTokenResponse{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FcmTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmTokenResponse) ProtoMessage() {}

func (x *FcmTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmTokenResponse.ProtoReflect.Descriptor instead.
func (*FcmTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *FcmTokenResponse) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationName  string                 `protobuf:"bytes,3,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *Location) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Location) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Location) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

type CreateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationName  string                 `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationRequest) Reset() {
	*x = CreateLocationRequest{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationRequest) ProtoMessage() {}

func (x *CreateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLocationRequest) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	LocationName  string                 `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateLocationRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

type LocationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationIdRequest) Reset() {
	*x = LocationIdRequest{}
	mi := &file_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationIdRequest) ProtoMessage() {}

func (x *LocationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationIdRequest.ProtoReflect.Descriptor instead.
func (*LocationIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *LocationIdRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type LocationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationListResponse) Reset() {
	*x = LocationListResponse{}
	mi := &file_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationListResponse) ProtoMessage() {}

func (x *LocationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationListResponse.ProtoReflect.Descriptor instead.
func (*LocationListResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *LocationListResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type Greenhouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Greenhouse) Reset() {
	*x = Greenhouse{}
	mi := &file_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Greenhouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greenhouse) ProtoMessage() {}

func (x *Greenhouse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greenhouse.ProtoReflect.Descriptor instead.
func (*Greenhouse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *Greenhouse) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *Greenhouse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Greenhouse) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Greenhouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateGreenhouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGreenhouseRequest) Reset() {
	*x = CreateGreenhouseRequest{}
	mi := &file_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGreenhouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGreenhouseRequest) ProtoMessage() {}

func (x *CreateGreenhouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGreenhouseRequest.ProtoReflect.Descriptor instead.
func (*CreateGreenhouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGreenhouseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateGreenhouseRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateGreenhouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateGreenhouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGreenhouseRequest) Reset() {
	*x = UpdateGreenhouseRequest{}
	mi := &file_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGreenhouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGreenhouseRequest) ProtoMessage() {}

func (x *UpdateGreenhouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGreenhouseRequest.ProtoReflect.Descriptor instead.
func (*UpdateGreenhouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateGreenhouseRequest) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *UpdateGreenhouseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGreenhouseRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type GreenhouseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreenhouseIdRequest) Reset() {
	*x = GreenhouseIdRequest{}
	mi := &file_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreenhouseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreenhouseIdRequest) ProtoMessage() {}

func (x *GreenhouseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreenhouseIdRequest.ProtoReflect.Descriptor instead.
func (*GreenhouseIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *GreenhouseIdRequest) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

type GreenhouseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreenhouseListRequest) Reset() {
	*x = GreenhouseListRequest{}
	mi := &file_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreenhouseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreenhouseListRequest) ProtoMessage() {}

func (x *GreenhouseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreenhouseListRequest.ProtoReflect.Descriptor instead.
func (*GreenhouseListRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *GreenhouseListRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type GreenhouseListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greenhouses   []*Greenhouse          `protobuf:"bytes,1,rep,name=greenhouses,proto3" json:"greenhouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreenhouseListResponse) Reset() {
	*x = GreenhouseListResponse{}
	mi := &file_proto_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreenhouseListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreenhouseListResponse) ProtoMessage() {}

func (x *GreenhouseListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreenhouseListResponse.ProtoReflect.Descriptor instead.
func (*GreenhouseListResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *GreenhouseListResponse) GetGreenhouses() []*Greenhouse {
	if x != nil {
		return x.Greenhouses
	}
	return nil
}

type Threshold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThresholdId   string                 `protobuf:"bytes,1,opt,name=threshold_id,json=thresholdId,proto3" json:"threshold_id,omitempty"`
	GreenhouseId  string                 `protobuf:"bytes,2,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	SensorType    string                 `protobuf:"bytes,3,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Min           float32                `protobuf:"fixed32,4,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,5,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threshold) Reset() {
	*x = Threshold{}
	mi := &file_proto_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threshold) ProtoMessage() {}

func (x *Threshold) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threshold.ProtoReflect.Descriptor instead.
func (*Threshold) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *Threshold) GetThresholdId() string {
	if x != nil {
		return x.ThresholdId
	}
	return ""
}

func (x *Threshold) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *Threshold) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *Threshold) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Threshold) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type CreateThresholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	SensorType    string                 `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Min           float32                `protobuf:"fixed32,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThresholdRequest) Reset() {
	*x = CreateThresholdRequest{}
	mi := &file_proto_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThresholdRequest) ProtoMessage() {}

func (x *CreateThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThresholdRequest.ProtoReflect.Descriptor instead.
func (*CreateThresholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{24}
}

func (x *CreateThresholdRequest) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *CreateThresholdRequest) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *CreateThresholdRequest) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *CreateThresholdRequest) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type UpdateThresholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThresholdId   string                 `protobuf:"bytes,1,opt,name=threshold_id,json=thresholdId,proto3" json:"threshold_id,omitempty"`
	Min           float32                `protobuf:"fixed32,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateThresholdRequest) Reset() {
	*x = UpdateThresholdRequest{}
	mi := &file_proto_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThresholdRequest) ProtoMessage() {}

func (x *UpdateThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThresholdRequest.ProtoReflect.Descriptor instead.
func (*UpdateThresholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateThresholdRequest) GetThresholdId() string {
	if x != nil {
		return x.ThresholdId
	}
	return ""
}

func (x *UpdateThresholdRequest) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *UpdateThresholdRequest) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ThresholdIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThresholdId   string                 `protobuf:"bytes,1,opt,name=threshold_id,json=thresholdId,proto3" json:"threshold_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdIdRequest) Reset() {
	*x = ThresholdIdRequest{}
	mi := &file_proto_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdIdRequest) ProtoMessage() {}

func (x *ThresholdIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdIdRequest.ProtoReflect.Descriptor instead.
func (*ThresholdIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *ThresholdIdRequest) GetThresholdId() string {
	if x != nil {
		return x.ThresholdId
	}
	return ""
}

type ThresholdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	SensorType    string                 `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdRequest) Reset() {
	*x = ThresholdRequest{}
	mi := &file_proto_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdRequest) ProtoMessage() {}

func (x *ThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdRequest.ProtoReflect.Descriptor instead.
func (*ThresholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{27}
}

func (x *ThresholdRequest) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *ThresholdRequest) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

type ThresholdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float32                `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdResponse) Reset() {
	*x = ThresholdResponse{}
	mi := &file_proto_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdResponse) ProtoMessage() {}

func (x *ThresholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdResponse.ProtoReflect.Descriptor instead.
func (*ThresholdResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{28}
}

func (x *ThresholdResponse) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ThresholdResponse) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SensorThreshold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorType    string                 `protobuf:"bytes,1,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Min           float32                `protobuf:"fixed32,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorThreshold) Reset() {
	*x = SensorThreshold{}
	mi := &file_proto_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorThreshold) ProtoMessage() {}

func (x *SensorThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorThreshold.ProtoReflect.Descriptor instead.
func (*SensorThreshold) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{29}
}

func (x *SensorThreshold) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorThreshold) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SensorThreshold) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SettingsResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SoundEnabled               bool                   `protobuf:"varint,1,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	WeatherNotifications       bool                   `protobuf:"varint,2,opt,name=weather_notifications,json=weatherNotifications,proto3" json:"weather_notifications,omitempty"`
	SensorFailureNotifications bool                   `protobuf:"varint,3,opt,name=sensor_failure_notifications,json=sensorFailureNotifications,proto3" json:"sensor_failure_notifications,omitempty"`
	Thresholds                 []*SensorThreshold     `protobuf:"bytes,4,rep,name=thresholds,proto3" json:"thresholds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_proto_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{30}
}

func (x *SettingsResponse) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *SettingsResponse) GetWeatherNotifications() bool {
	if x != nil {
		return x.WeatherNotifications
	}
	return false
}

func (x *SettingsResponse) GetSensorFailureNotifications() bool {
	if x != nil {
		return x.SensorFailureNotifications
	}
	return false
}

func (x *SettingsResponse) GetThresholds() []*SensorThreshold {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

type UpdateSettingsRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	UserId                     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SoundEnabled               bool                   `protobuf:"varint,2,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	WeatherNotifications       bool                   `protobuf:"varint,3,opt,name=weather_notifications,json=weatherNotifications,proto3" json:"weather_notifications,omitempty"`
	SensorFailureNotifications bool                   `protobuf:"varint,4,opt,name=sensor_failure_notifications,json=sensorFailureNotifications,proto3" json:"sensor_failure_notifications,omitempty"`
	Thresholds                 []*SensorThreshold     `protobuf:"bytes,5,rep,name=thresholds,proto3" json:"thresholds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_proto_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSettingsRequest) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UpdateSettingsRequest) GetWeatherNotifications() bool {
	if x != nil {
		return x.WeatherNotifications
	}
	return false
}

func (x *UpdateSettingsRequest) GetSensorFailureNotifications() bool {
	if x != nil {
		return x.SensorFailureNotifications
	}
	return false
}

func (x *UpdateSettingsRequest) GetThresholds() []*SensorThreshold {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

type Sensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	GreenhouseId  string                 `protobuf:"bytes,2,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	SensorType    string                 `protobuf:"bytes,3,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sensor) Reset() {
	*x = Sensor{}
	mi := &file_proto_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sensor) ProtoMessage() {}

func (x *Sensor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sensor.ProtoReflect.Descriptor instead.
func (*Sensor) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{32}
}

func (x *Sensor) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *Sensor) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *Sensor) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *Sensor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	SensorType    string                 `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSensorRequest) Reset() {
	*x = CreateSensorRequest{}
	mi := &file_proto_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSensorRequest) ProtoMessage() {}

func (x *CreateSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSensorRequest.ProtoReflect.Descriptor instead.
func (*CreateSensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{33}
}

func (x *CreateSensorRequest) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

func (x *CreateSensorRequest) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *CreateSensorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSensorRequest) Reset() {
	*x = UpdateSensorRequest{}
	mi := &file_proto_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSensorRequest) ProtoMessage() {}

func (x *UpdateSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSensorRequest.ProtoReflect.Descriptor instead.
func (*UpdateSensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateSensorRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *UpdateSensorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SensorIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorIdRequest) Reset() {
	*x = SensorIdRequest{}
	mi := &file_proto_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorIdRequest) ProtoMessage() {}

func (x *SensorIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorIdRequest.ProtoReflect.Descriptor instead.
func (*SensorIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{35}
}

func (x *SensorIdRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type SensorListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GreenhouseId  string                 `protobuf:"bytes,1,opt,name=greenhouse_id,json=greenhouseId,proto3" json:"greenhouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorListRequest) Reset() {
	*x = SensorListRequest{}
	mi := &file_proto_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorListRequest) ProtoMessage() {}

func (x *SensorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorListRequest.ProtoReflect.Descriptor instead.
func (*SensorListRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{36}
}

func (x *SensorListRequest) GetGreenhouseId() string {
	if x != nil {
		return x.GreenhouseId
	}
	return ""
}

type SensorListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sensors       []*Sensor              `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorListResponse) Reset() {
	*x = SensorListResponse{}
	mi := &file_proto_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorListResponse) ProtoMessage() {}

func (x *SensorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorListResponse.ProtoReflect.Descriptor instead.
func (*SensorListResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{37}
}

func (x *SensorListResponse) GetSensors() []*Sensor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"D\n" +
	"\x1dUserInfoRequestFromGreenhouse\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\"\xbb\x01\n" +
	"\x1eUserInfoResponseFromGreenhouse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfcm_token\x18\x02 \x01(\tR\bfcmToken\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\x12#\n" +
	"\rlocation_name\x18\x05 \x01(\tR\flocationName\"\v\n" +
	"\tUserEmpty\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x81\x01\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\"\xb2\x01\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfcm_token\x18\x04 \x01(\tR\bfcmToken\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12#\n" +
	"\rpassword_hash\x18\x06 \x01(\tR\fpasswordHash\"u\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"M\n" +
	"\x13UpdateAvatarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\"/\n" +
	"\x0eAvatarResponse\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x01 \x01(\tR\tavatarUrl\"M\n" +
	"\x15UpdateFcmTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfcm_token\x18\x02 \x01(\tR\bfcmToken\"/\n" +
	"\x10FcmTokenResponse\x12\x1b\n" +
	"\tfcm_token\x18\x01 \x01(\tR\bfcmToken\"i\n" +
	"\bLocation\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rlocation_name\x18\x03 \x01(\tR\flocationName\"U\n" +
	"\x15CreateLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rlocation_name\x18\x02 \x01(\tR\flocationName\"]\n" +
	"\x15UpdateLocationRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12#\n" +
	"\rlocation_name\x18\x02 \x01(\tR\flocationName\"4\n" +
	"\x11LocationIdRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\"D\n" +
	"\x14LocationListResponse\x12,\n" +
	"\tlocations\x18\x01 \x03(\v2\x0e.user.LocationR\tlocations\"\x7f\n" +
	"\n" +
	"Greenhouse\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"g\n" +
	"\x17CreateGreenhouseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"s\n" +
	"\x17UpdateGreenhouseRequest\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\":\n" +
	"\x13GreenhouseIdRequest\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\"8\n" +
	"\x15GreenhouseListRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\"L\n" +
	"\x16GreenhouseListResponse\x122\n" +
	"\vgreenhouses\x18\x01 \x03(\v2\x10.user.GreenhouseR\vgreenhouses\"\x98\x01\n" +
	"\tThreshold\x12!\n" +
	"\fthreshold_id\x18\x01 \x01(\tR\vthresholdId\x12#\n" +
	"\rgreenhouse_id\x18\x02 \x01(\tR\fgreenhouseId\x12\x1f\n" +
	"\vsensor_type\x18\x03 \x01(\tR\n" +
	"sensorType\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x02R\x03max\"\x82\x01\n" +
	"\x16CreateThresholdRequest\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x02R\x03max\"_\n" +
	"\x16UpdateThresholdRequest\x12!\n" +
	"\fthreshold_id\x18\x01 \x01(\tR\vthresholdId\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x02R\x03max\"7\n" +
	"\x12ThresholdIdRequest\x12!\n" +
	"\fthreshold_id\x18\x01 \x01(\tR\vthresholdId\"X\n" +
	"\x10ThresholdRequest\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\"7\n" +
	"\x11ThresholdResponse\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x02R\x03max\"V\n" +
	"\x0fSensorThreshold\x12\x1f\n" +
	"\vsensor_type\x18\x01 \x01(\tR\n" +
	"sensorType\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x02R\x03max\"\xe5\x01\n" +
	"\x10SettingsResponse\x12#\n" +
	"\rsound_enabled\x18\x01 \x01(\bR\fsoundEnabled\x123\n" +
	"\x15weather_notifications\x18\x02 \x01(\bR\x14weatherNotifications\x12@\n" +
	"\x1csensor_failure_notifications\x18\x03 \x01(\bR\x1asensorFailureNotifications\x125\n" +
	"\n" +
	"thresholds\x18\x04 \x03(\v2\x15.user.SensorThresholdR\n" +
	"thresholds\"\x83\x02\n" +
	"\x15UpdateSettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rsound_enabled\x18\x02 \x01(\bR\fsoundEnabled\x123\n" +
	"\x15weather_notifications\x18\x03 \x01(\bR\x14weatherNotifications\x12@\n" +
	"\x1csensor_failure_notifications\x18\x04 \x01(\bR\x1asensorFailureNotifications\x125\n" +
	"\n" +
	"thresholds\x18\x05 \x03(\v2\x15.user.SensorThresholdR\n" +
	"thresholds\"\x7f\n" +
	"\x06Sensor\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12#\n" +
	"\rgreenhouse_id\x18\x02 \x01(\tR\fgreenhouseId\x12\x1f\n" +
	"\vsensor_type\x18\x03 \x01(\tR\n" +
	"sensorType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"o\n" +
	"\x13CreateSensorRequest\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"F\n" +
	"\x13UpdateSensorRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\x0fSensorIdRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\"8\n" +
	"\x11SensorListRequest\x12#\n" +
	"\rgreenhouse_id\x18\x01 \x01(\tR\fgreenhouseId\"<\n" +
	"\x12SensorListResponse\x12&\n" +
	"\asensors\x18\x01 \x03(\v2\f.user.SensorR\asensors2\xb8\x0e\n" +
	"\vUserService\x129\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x122\n" +
	"\aGetUser\x12\x13.user.UserIdRequest\x1a\x12.user.UserResponse\x126\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x0f.user.UserEmpty\x122\n" +
	"\n" +
	"DeleteUser\x12\x13.user.UserIdRequest\x1a\x0f.user.UserEmpty\x12:\n" +
	"\fUpdateAvatar\x12\x19.user.UpdateAvatarRequest\x1a\x0f.user.UserEmpty\x126\n" +
	"\tGetAvatar\x12\x13.user.UserIdRequest\x1a\x14.user.AvatarResponse\x12>\n" +
	"\x0eUpdateFcmToken\x12\x1b.user.UpdateFcmTokenRequest\x1a\x0f.user.UserEmpty\x12:\n" +
	"\vGetFcmToken\x12\x13.user.UserIdRequest\x1a\x16.user.FcmTokenResponse\x12=\n" +
	"\x0eCreateLocation\x12\x1b.user.CreateLocationRequest\x1a\x0e.user.Location\x12?\n" +
	"\fGetLocations\x12\x13.user.UserIdRequest\x1a\x1a.user.LocationListResponse\x12>\n" +
	"\x0eUpdateLocation\x12\x1b.user.UpdateLocationRequest\x1a\x0f.user.UserEmpty\x12:\n" +
	"\x0eDeleteLocation\x12\x17.user.LocationIdRequest\x1a\x0f.user.UserEmpty\x12C\n" +
	"\x10CreateGreenhouse\x12\x1d.user.CreateGreenhouseRequest\x1a\x10.user.Greenhouse\x12K\n" +
	"\x0eGetGreenhouses\x12\x1b.user.GreenhouseListRequest\x1a\x1c.user.GreenhouseListResponse\x12B\n" +
	"\x10UpdateGreenhouse\x12\x1d.user.UpdateGreenhouseRequest\x1a\x0f.user.UserEmpty\x12>\n" +
	"\x10DeleteGreenhouse\x12\x19.user.GreenhouseIdRequest\x1a\x0f.user.UserEmpty\x12@\n" +
	"\x0fCreateThreshold\x12\x1c.user.CreateThresholdRequest\x1a\x0f.user.Threshold\x12@\n" +
	"\rGetThresholds\x12\x16.user.ThresholdRequest\x1a\x17.user.ThresholdResponse\x12@\n" +
	"\x0fUpdateThreshold\x12\x1c.user.UpdateThresholdRequest\x1a\x0f.user.UserEmpty\x12<\n" +
	"\x0fDeleteThreshold\x12\x18.user.ThresholdIdRequest\x1a\x0f.user.UserEmpty\x12:\n" +
	"\vGetSettings\x12\x13.user.UserIdRequest\x1a\x16.user.SettingsResponse\x12>\n" +
	"\x0eUpdateSettings\x12\x1b.user.UpdateSettingsRequest\x1a\x0f.user.UserEmpty\x12f\n" +
	"\x19GetUserInfoFromGreenhouse\x12#.user.UserInfoRequestFromGreenhouse\x1a$.user.UserInfoResponseFromGreenhouse\x128\n" +
	"\x0eGetUserByEmail\x12\x12.user.EmailRequest\x1a\x12.user.UserResponse\x127\n" +
	"\fCreateSensor\x12\x19.user.CreateSensorRequest\x1a\f.user.Sensor\x12:\n" +
	"\fUpdateSensor\x12\x19.user.UpdateSensorRequest\x1a\x0f.user.UserEmpty\x126\n" +
	"\fDeleteSensor\x12\x15.user.SensorIdRequest\x1a\x0f.user.UserEmpty\x12K\n" +
	"\x16GetSensorsByGreenhouse\x12\x17.user.SensorListRequest\x1a\x18.user.SensorListResponse\x120\n" +
	"\tGetSensor\x12\x15.user.SensorIdRequest\x1a\f.user.SensorB\x13Z\x11proto/user;userpbb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_user_proto_goTypes = []any{
	(*EmailRequest)(nil),                   // 0: user.EmailRequest
	(*UserInfoRequestFromGreenhouse)(nil),  // 1: user.UserInfoRequestFromGreenhouse
	(*UserInfoResponseFromGreenhouse)(nil), // 2: user.UserInfoResponseFromGreenhouse
	(*UserEmpty)(nil),                      // 3: user.UserEmpty
	(*UserIdRequest)(nil),                  // 4: user.UserIdRequest
	(*CreateUserRequest)(nil),              // 5: user.CreateUserRequest
	(*UserResponse)(nil),                   // 6: user.UserResponse
	(*UpdateUserRequest)(nil),              // 7: user.UpdateUserRequest
	(*UpdateAvatarRequest)(nil),            // 8: user.UpdateAvatarRequest
	(*AvatarResponse)(nil),                 // 9: user.AvatarResponse
	(*UpdateFcmTokenRequest)(nil),          // 10: user.UpdateFcmTokenRequest
	(*FcmTokenResponse)(nil),               // 11: user.FcmTokenResponse
	(*Location)(nil),                       // 12: user.Location
	(*CreateLocationRequest)(nil),          // 13: user.CreateLocationRequest
	(*UpdateLocationRequest)(nil),          // 14: user.UpdateLocationRequest
	(*LocationIdRequest)(nil),              // 15: user.LocationIdRequest
	(*LocationListResponse)(nil),           // 16: user.LocationListResponse
	(*Greenhouse)(nil),                     // 17: user.Greenhouse
	(*CreateGreenhouseRequest)(nil),        // 18: user.CreateGreenhouseRequest
	(*UpdateGreenhouseRequest)(nil),        // 19: user.UpdateGreenhouseRequest
	(*GreenhouseIdRequest)(nil),            // 20: user.GreenhouseIdRequest
	(*GreenhouseListRequest)(nil),          // 21: user.GreenhouseListRequest
	(*GreenhouseListResponse)(nil),         // 22: user.GreenhouseListResponse
	(*Threshold)(nil),                      // 23: user.Threshold
	(*CreateThresholdRequest)(nil),         // 24: user.CreateThresholdRequest
	(*UpdateThresholdRequest)(nil),         // 25: user.UpdateThresholdRequest
	(*ThresholdIdRequest)(nil),             // 26: user.ThresholdIdRequest
	(*ThresholdRequest)(nil),               // 27: user.ThresholdRequest
	(*ThresholdResponse)(nil),              // 28: user.ThresholdResponse
	(*SensorThreshold)(nil),                // 29: user.SensorThreshold
	(*SettingsResponse)(nil),               // 30: user.SettingsResponse
	(*UpdateSettingsRequest)(nil),          // 31: user.UpdateSettingsRequest
	(*Sensor)(nil),                         // 32: user.Sensor
	(*CreateSensorRequest)(nil),            // 33: user.CreateSensorRequest
	(*UpdateSensorRequest)(nil),            // 34: user.UpdateSensorRequest
	(*SensorIdRequest)(nil),                // 35: user.SensorIdRequest
	(*SensorListRequest)(nil),              // 36: user.SensorListRequest
	(*SensorListResponse)(nil),             // 37: user.SensorListResponse
}
var file_proto_user_proto_depIdxs = []int32{
	12, // 0: user.LocationListResponse.locations:type_name -> user.Location
	17, // 1: user.GreenhouseListResponse.greenhouses:type_name -> user.Greenhouse
	29, // 2: user.SettingsResponse.thresholds:type_name -> user.SensorThreshold
	29, // 3: user.UpdateSettingsRequest.thresholds:type_name -> user.SensorThreshold
	32, // 4: user.SensorListResponse.sensors:type_name -> user.Sensor
	5,  // 5: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	4,  // 6: user.UserService.GetUser:input_type -> user.UserIdRequest
	7,  // 7: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	4,  // 8: user.UserService.DeleteUser:input_type -> user.UserIdRequest
	8,  // 9: user.UserService.UpdateAvatar:input_type -> user.UpdateAvatarRequest
	4,  // 10: user.UserService.GetAvatar:input_type -> user.UserIdRequest
	10, // 11: user.UserService.UpdateFcmToken:input_type -> user.UpdateFcmTokenRequest
	4,  // 12: user.UserService.GetFcmToken:input_type -> user.UserIdRequest
	13, // 13: user.UserService.CreateLocation:input_type -> user.CreateLocationRequest
	4,  // 14: user.UserService.GetLocations:input_type -> user.UserIdRequest
	14, // 15: user.UserService.UpdateLocation:input_type -> user.UpdateLocationRequest
	15, // 16: user.UserService.DeleteLocation:input_type -> user.LocationIdRequest
	18, // 17: user.UserService.CreateGreenhouse:input_type -> user.CreateGreenhouseRequest
	21, // 18: user.UserService.GetGreenhouses:input_type -> user.GreenhouseListRequest
	19, // 19: user.UserService.UpdateGreenhouse:input_type -> user.UpdateGreenhouseRequest
	20, // 20: user.UserService.DeleteGreenhouse:input_type -> user.GreenhouseIdRequest
	24, // 21: user.UserService.CreateThreshold:input_type -> user.CreateThresholdRequest
	27, // 22: user.UserService.GetThresholds:input_type -> user.ThresholdRequest
	25, // 23: user.UserService.UpdateThreshold:input_type -> user.UpdateThresholdRequest
	26, // 24: user.UserService.DeleteThreshold:input_type -> user.ThresholdIdRequest
	4,  // 25: user.UserService.GetSettings:input_type -> user.UserIdRequest
	31, // 26: user.UserService.UpdateSettings:input_type -> user.UpdateSettingsRequest
	1,  // 27: user.UserService.GetUserInfoFromGreenhouse:input_type -> user.UserInfoRequestFromGreenhouse
	0,  // 28: user.UserService.GetUserByEmail:input_type -> user.EmailRequest
	33, // 29: user.UserService.CreateSensor:input_type -> user.CreateSensorRequest
	34, // 30: user.UserService.UpdateSensor:input_type -> user.UpdateSensorRequest
	35, // 31: user.UserService.DeleteSensor:input_type -> user.SensorIdRequest
	36, // 32: user.UserService.GetSensorsByGreenhouse:input_type -> user.SensorListRequest
	35, // 33: user.UserService.GetSensor:input_type -> user.SensorIdRequest
	6,  // 34: user.UserService.CreateUser:output_type -> user.UserResponse
	6,  // 35: user.UserService.GetUser:output_type -> user.UserResponse
	3,  // 36: user.UserService.UpdateUser:output_type -> user.UserEmpty
	3,  // 37: user.UserService.DeleteUser:output_type -> user.UserEmpty
	3,  // 38: user.UserService.UpdateAvatar:output_type -> user.UserEmpty
	9,  // 39: user.UserService.GetAvatar:output_type -> user.AvatarResponse
	3,  // 40: user.UserService.UpdateFcmToken:output_type -> user.UserEmpty
	11, // 41: user.UserService.GetFcmToken:output_type -> user.FcmTokenResponse
	12, // 42: user.UserService.CreateLocation:output_type -> user.Location
	16, // 43: user.UserService.GetLocations:output_type -> user.LocationListResponse
	3,  // 44: user.UserService.UpdateLocation:output_type -> user.UserEmpty
	3,  // 45: user.UserService.DeleteLocation:output_type -> user.UserEmpty
	17, // 46: user.UserService.CreateGreenhouse:output_type -> user.Greenhouse
	22, // 47: user.UserService.GetGreenhouses:output_type -> user.GreenhouseListResponse
	3,  // 48: user.UserService.UpdateGreenhouse:output_type -> user.UserEmpty
	3,  // 49: user.UserService.DeleteGreenhouse:output_type -> user.UserEmpty
	23, // 50: user.UserService.CreateThreshold:output_type -> user.Threshold
	28, // 51: user.UserService.GetThresholds:output_type -> user.ThresholdResponse
	3,  // 52: user.UserService.UpdateThreshold:output_type -> user.UserEmpty
	3,  // 53: user.UserService.DeleteThreshold:output_type -> user.UserEmpty
	30, // 54: user.UserService.GetSettings:output_type -> user.SettingsResponse
	3,  // 55: user.UserService.UpdateSettings:output_type -> user.UserEmpty
	2,  // 56: user.UserService.GetUserInfoFromGreenhouse:output_type -> user.UserInfoResponseFromGreenhouse
	6,  // 57: user.UserService.GetUserByEmail:output_type -> user.UserResponse
	32, // 58: user.UserService.CreateSensor:output_type -> user.Sensor
	3,  // 59: user.UserService.UpdateSensor:output_type -> user.UserEmpty
	3,  // 60: user.UserService.DeleteSensor:output_type -> user.UserEmpty
	37, // 61: user.UserService.GetSensorsByGreenhouse:output_type -> user.SensorListResponse
	32, // 62: user.UserService.GetSensor:output_type -> user.Sensor
	34, // [34:63] is the sub-list for method output_type
	5,  // [5:34] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
